mongodb:
    host: localhost
    port: 27017
    username: beepaste
    password: my secret password
    database: beepaste

redis:
    host: localhost
    port: 6379
    password: my secret password

api:
    use_anonymous: yes

web_server:
    port : 8080
    host : localhost
    workers: 8
    log_config:
        version: 1
        formatters:
            beepasteFormater:
                format: "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
                datefmt: '%Y/%m/%d %H:%M:%S'
        handlers:
            file:
                class : logging.FileHandler
                formatter: beepasteFormater
                level: DEBUG
                filename: sanic.log
        root:
            level: DEBUG
            handlers: [file]

logger:
    version: 1
    formatters:
        beepasteFormater:
            format: "%(asctime)s %(name)-12s %(levelname)-8s %(message)s"
            datefmt: '%Y/%m/%d %H:%M:%S'
    handlers:
        file:
            class : logging.FileHandler
            formatter: beepasteFormater
            level: INFO
            filename: beepaste.log
    loggers:
        beepaste:
            level: INFO
            handlers: [file]
    root:
        level: INFO
        handlers: [file]
