mongodb:
    host: localhost
    port: 27017
    username: beepaste
    password: my secret password
    database: beepaste

redis:
    host: localhost
    port: 6379
    password: my secret password 

api:
    use_anonymous: yes

web_server:
    port : 8080
    host : localhost
    workers: 8
    log_config: None

logger:
    log_file : '/var/log/beepaste.log'
    log_level: "INFO"
    format=%(asctime)s %(name)-12s %(levelname)-8s %(message)s